style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/syntro-opensource/silverstripe-ssto
options:
  commits:
    filters:
      Type:
        - add
        - fix
        - change
        - remove
        - deprecate
        - Bump
        - Update
  commit_groups:
    title_maps:
      add: ğŸ° Added
      fix: ğŸ Fixed
      change: ğŸ”§ Changed
      deprecate: ğŸ’€ Deprecated
      remove: ğŸ—‘ Removed
      Bump: ğŸ§¬ NPM Dependencies
      Update: ğŸ§¬ Composer Dependencies
  header:
    pattern: "^(\\w*)\\:?\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
